name: referral
version: '1.0-SNAPSHOT'
main: plugin.referral.Referral
api-version: '1.21'
authors: [ Giovanni Cirigliano ]
description: referral plugin
website: https://github.com/shokk47
commands:
  getReferral:
    description: Ottieni il tuo codice referral o creane uno nuovo
    usage: /getReferral
  invite:
    description: Invita un giocatore con il tuo codice referral
    usage: /invite <player>
  checkInvites:
    description: Controlla quanti giocatori hai invitato
    usage: /checkInvites